/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;
import exnet.portfolio.exapi.*;

public class ExAPIHttpClientTest {
    @Test 
    public void testGetAssets() {
        ExAPIHttpClient client = new ExAPIHttpClient();
        String result = client.GetSpotAssets();
        assertEquals(result, "1");
    }
}
